# Generated by Django 6.1.1 on 2026-09-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic_type', models.CharField(choices=[('project', 'Project'), ('area', 'Area'), ('process', 'Process'), ('person', 'Person'), ('customer', 'Customer'), ('opportunity', 'Opportunity')], default='project', max_length=20)),
                ('one_liner', models.CharField(blank=True, max_length=300)),
                ('related_people', models.CharField(blank=True, help_text='Comma-separated names, plain text for MVP', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='core.topic')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('source_files', models.JSONField(blank=True, default=list)),
                ('is_llm', models.BooleanField(default=True)),
                ('generation_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.topic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('source_method', models.CharField(choices=[('folder', 'Lookup folder'), ('upload', 'Uploaded file'), ('paste', 'Pasted text')], default='folder', max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('extraction_error', models.CharField(blank=True, max_length=300)),
                ('first_added_at', models.DateTimeField(auto_now_add=True)),
                ('last_ingested_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.topic')),
            ],
            options={
                'ordering': ['-first_added_at'],
                'unique_together': {('topic', 'path')},
            },
        ),
    ]
