# Generated by Django 6.1.1 on 2026-09-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestedfile',
            name='source_method',
            field=models.CharField(choices=[('folder', 'Lookup folder'), ('upload', 'Uploaded file'), ('paste', 'Pasted text'), ('folder_upload', 'Uploaded folder')], default='folder', max_length=20),
        ),
        migrations.CreateModel(
            name='ExtractedMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(blank=True, max_length=300)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('meeting_time', models.CharField(blank=True, max_length=20)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('agenda', models.TextField(blank=True)),
                ('achieved', models.TextField(blank=True)),
                ('employee_hours', models.JSONField(blank=True, default=list)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('ingested_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='core.ingestedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('payroll_approval', 'Payroll Approval')], default='payroll_approval', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('computed_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
