# Generated by Django 6.1.1 on 2026-09-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ingestedfile_source_method_extractedmeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('assignee', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('done', 'Completed')], default='backlog', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.ingestedfile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.topic')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
