# Generated by Django 6.1.1 on 2026-09-18 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globalchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestedfile',
            name='source_method',
            field=models.CharField(choices=[('folder', 'Lookup folder'), ('upload', 'Uploaded file'), ('paste', 'Pasted text'), ('folder_upload', 'Uploaded folder'), ('email_import', 'Email import'), ('calendar_import', 'Calendar import')], default='folder', max_length=20),
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scanning', 'Scanning files'), ('extracting', 'Extracting details'), ('done', 'Done'), ('error', 'Error')], default='scanning', max_length=12)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('scanned', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('unchanged', models.IntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='core.topic')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
