# Generated by Django 6.1.1 on 2026-09-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ingestedfile_source_method_scanjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_now', models.TextField(blank=True)),
                ('current_state', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('customer_thoughts', models.TextField(blank=True)),
                ('promises_made', models.TextField(blank=True)),
                ('next_step', models.TextField(blank=True)),
                ('risks_and_gaps', models.TextField(blank=True)),
                ('sources_used', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='core.topic')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
