# Generated by Django 6.1.1 on 2026-09-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_loop_casesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('requested', 'Requested — Pending Review'), ('connected', 'Connected')], default='not_connected', max_length=20)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
