# Generated by Django 6.1.1 on 2026-09-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sharedcontextproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedContextProject',
        ),
    ]
