# Generated by Django 6.1.1 on 2026-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_sharedcontextproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesummary',
            name='is_manual_edit',
            field=models.BooleanField(default=False, help_text="True when this row came from a CSV re-import (a person's own edit on top of the AI's first-level draft), not a fresh AI generation - Venki's own 'creation part, editing part' split, 22 Sep sprint meeting."),
        ),
    ]
