# Generated by Django 6.1.1 on 2026-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_casesummary_is_manual_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesummary',
            name='field_sources',
            field=models.JSONField(blank=True, default=dict, help_text="Per-field citations, e.g. {'current_state': ['path1', 'path2']} - lets the brief page show a source link right next to the paragraph it actually backs, instead of one undifferentiated file list at the bottom (real, direct feedback: 'cluttered, I cannot understand which paragraph is referring to what file'). Keyed by the same field names as this model's own text fields; a field missing here just renders with no inline source."),
        ),
    ]
