# Generated by Django 6.1.1 on 2026-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_casesummary_field_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesummary',
            name='answer_summary',
            field=models.TextField(blank=True, help_text='The direct 2-4 sentence answer to the question asked, for the top of the brief.'),
        ),
    ]
