# Generated by Django 6.1.1 on 2026-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_casesummary_answer_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='added',
            field=models.IntegerField(default=0, help_text="Brand new files never seen before this scan - distinct from 'updated' (an existing file whose content changed). The 'X new files found' count a person can actually act on, not lumped in with edits to files already known."),
        ),
    ]
